version: '3.8'

services:
  # Neon Local Database Proxy
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    networks:
      - acquisitions-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # volumes:
      # Optional: Persist branch metadata between container restarts
      # Uncomment the lines below to enable persistent branches per git branch
      # - ./.neon_local:/tmp/.neon_local
      # - ./.git/HEAD:/tmp/.git/HEAD:ro

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-dev
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - acquisitions-network
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  acquisitions-network:
    driver: bridge
    name: acquisitions-dev-network

volumes:
  neon-local-data:
    name: acquisitions-neon-local-data